/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <bits/stdc++.h>

using namespace std;

class dmoj_rgpc1 {
public:
    void solve(istream& in, ostream& out) {
        int N, M;
        in >> N >> M;
        if (N % M == 0) {
            out << "yes " << N / M << "\n";
        } else {
            int Y;
            for (Y = M; N % Y != 0; ++Y);
            out << "no " << Y - M << "\n";
        }
    }
};

int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);
    dmoj_rgpc1 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
