/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin64b
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>

using namespace std;

class TaskB {
public:
    //5819
    void solve(istream& in, ostream& out) {
        string guess = "0000";
        int bulls = 0, cows = 0;
        
        vector<char> dig;
        for (char c = '0'; c <= '9'; ++c) {
            cout << string(4, c) << endl;
            cin >> bulls >> cows;
            if (bulls == 1) {
                dig.push_back(c);
            }
        }
        for (int i = 0; i < 4; ++i) {
            guess[0] = dig[i];
            for (int j = 0; j < 4; ++j) {
                if (i == j) continue;
                guess[1] = dig[j];
                for (int k = 0; k < 4; ++k) {
                    if (k == j || k == i) continue;
                    guess[2] = dig[k];
                    for (int m = 0; m < 4; ++m) {
                        if (m == j || m == k || m == i) continue;
                        guess[3] = dig[m];
                        cout << guess << endl;
                        fflush(stdout);
                        cin >> bulls >> cows;
                        if (bulls == 4) {
                            return;
                        }
                    }
                }
            }
        }

        
    }
};


int main() {
    std::ios::sync_with_stdio(false);

    TaskB solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
