/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <cassert>

using namespace std;

class TaskA {
public:
    void solve(istream& in, ostream& out) {
        string vic1, vic2;
        int n;
        in >> vic1 >> vic2 >> n;
        vector<pair<string,string>> vics(n);
        for (int i = 0; i < n; ++i) {
            in >> vics[i].first >> vics[i].second;
        }
    
        pair<string,string> cur = make_pair(vic1, vic2);
        for (int i = 0; i < n; ++i) {
            out << cur.first << " " << cur.second << "\n";
            if (vics[i].first == cur.first) {
                cur.first = vics[i].second;
            } else if (vics[i].first == cur.second) {
                cur.second = vics[i].second;
            }
        }
        out << cur.first << " " << cur.second << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false);

    TaskA solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
