/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class A122 {
private:
    bool isLucky(int x) {
        while (x) {
            if (x % 10 != 4 && x % 10 != 7) {
                return false;
            }
            x /= 10;
        }
        return true;
    }
public:
    void solve(istream& in, ostream& out) {
        int n;
        in >> n;
        for (int i = 4; i <= n; ++i) {
            if (isLucky(i) && n % i == 0) {
                out << "YES\n";
                return;
            }
        }
        out << "NO\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    A122 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
