/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class A204 {
private:
    long long F(long long r) {
        if (r < 10) {
            return r;
        }
        string s(to_string(r));
        int len = s.size();
        long long x = 0;
        if (len-2 > 0) {
            x = stoll(s.substr(1, len - 2));
        }
        
        long long res = 9;
        for (char d = '1'; d <= '9'; ++d) {
            for (int i = 0; i <= len - 2; ++i) {
                if (i < len - 2 || (i == len - 2 && d < s[0])) {
                    res += pow(10, i);
                } else if (i == len - 2 && d == s[0]) {
                    res += x;
                    res += d <= s[len-1];
                }
            }
        }
        return res;
    }
public:
    void solve(istream& in, ostream& out) {
        long long l, r;
        in >> l >> r;
        
        out << F(r) - F(l-1) << "\n";
        //cout << F(r) << " " << F(l-1) << endl;
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    A204 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
