/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class A230 {
public:
    void solve(istream& in, ostream& out) {
        int s, n;
        in >> s >> n;
        vector<pair<int,int>> v(n);
        for (int i = 0; i < n; ++i) {
            in >> v[i].first >> v[i].second;
        }
        sort(v.begin(), v.end());
        for (int i = 0; i < n; ++i) {
            if (s <= v[i].first) {
                out << "NO\n";
                return;
            }
            s += v[i].second;
        }
        out << "YES\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    A230 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
