/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <cassert>

using namespace std;

class D231 {
public:
    void solve(istream& in, ostream& out) {
        int x, y, z, x1, y1, z1;
        int a[6];
        in >> x >> y >> z >> x1 >> y1 >> z1;
        for (int i = 0; i < 6; ++i) {
            in >> a[i];
        }
        int sum = 0;
        if (x < 0) sum += a[4];
        else if (x > x1) sum += a[5];
        if (y < 0) sum += a[0];
        else if (y > y1) sum += a[1];
        if (z < 0) sum += a[2];
        else if (z > z1) sum += a[3];
        
        out << sum << endl;
    }
};


int main() {
    std::ios::sync_with_stdio(false);

    D231 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
