/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class C282 {
public:
    void solve(istream& in, ostream& out) {
        string a, b;
        in >> a >> b;
        int cnt1 = count(a.begin(), a.end(), '1'), cnt2 = count(b.begin(), b.end(), '1');
        
        if (a.size() != b.size()) {
            out << "NO\n";
        } else if (cnt1) {
            if (cnt2) {
                out << "YES\n";
            } else {
                out << "NO\n";
            }
        } else {
            if (!cnt2) {
                out << "YES\n";
            } else {
                out << "NO\n";
            }
        }
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    C282 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
