/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <cassert>

using namespace std;

class A334 {
public:
    void solve(istream& in, ostream& out) {
        int n;
        in >> n;
        
        for (int i = 0; i < n; ++i) {
            for (int j = i*n/2; j < i*n/2 + n/2; ++j) {
                out << j+1 << " ";
            }
            for (int j = n*n + 1 - (i+1)*n/2; j < n*n + 1 - (i+1)*n/2 + n/2; ++j) {
                out << j << " ";
            }
            out << endl;
        }
    }
};


int main() {
    std::ios::sync_with_stdio(false);

    A334 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
