/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>
#include <sstream>

using namespace std;

class A378 {
public:
    void solve(istream& in, ostream& out) {
        int a, b;
        in >> a >> b;
        int res1 = 0, res2 = 0, res3 = 0;
        for (int d = 1; d <= 6; ++d) {
            if (abs(a - d) < abs(b - d))
                ++res1;
            else if (abs(a - d) == abs(b - d))
                ++res2;
            else
                ++res3;
        }
        out << res1 << " " << res2 << " " << res3 << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);
    A378 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
