/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <cassert>

using namespace std;

class C401 {
public:
    void solve(istream& in, ostream& out) {
        int n, m;
        in >> n >> m;
        
        string s;
        while (n && m) {
            s += "01";
            --n;
            --m;
            
            if (m > n) {
                s += "1";
                --m;
            }
        }
        
        if (m >= 2) {
            s = "11" + s;
            m -= 2;
        } else if (m == 1) {
            s = "1" + s;
            --m;
        }
        if (n >= 1) {
            s += "0";
            --n;
        }
        if (n || m) {
            out << -1 << "\n";
        } else {
            out << s << "\n";
        }
    }
};


int main() {
    std::ios::sync_with_stdio(false);

    C401 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
