/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class A405 {
public:
    void solve(istream& in, ostream& out) {
        int n;
        in >> n;
        vector<int> a(n);
        for (int i = 0; i < n; ++i) {
            in >> a[i];
        }
        
        vector<int> row(101, 0);
        for (int j = 0; j < n; ++j) {
            for (int i = 100; i >= 0 && a[j]--; --i) {
                ++row[i];
            }
        }
        
        vector<int> column(n, 0);
        for (int i = 0; i <= 100; ++i) {
            for (int j = 0; j < row[i]; ++j) {
                ++column[n - 1 - j];
            }
        }
        
        for (int j = 0; j < n; ++j) {
            out << column[j] << " ";
        }
        out << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    A405 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
