/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>
#include <sstream>

using namespace std;

class A414 {
public:
    void solve(istream& in, ostream& out) {
        int n, k;
        in >> n >> k;
        if (n / 2 > k) {
            out << -1 << "\n";
            return;
        } else if (n == 1) {
            out << (k > 0 ? -1 : 1) << "\n";
            return;
        }
        vector<int> a(n);
        int score_first = k - (n / 2 - 1);
        a[0] = score_first;
        a[1] = 2 * score_first;
        for (int i = 2; i < n; ++i) {
            a[i] = a[i - 1] + 1;
        }
        for (int x : a) {
            out << x << " ";
        }
        out << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);
    A414 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
