/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>
#include <sstream>

using namespace std;

class A426 {
public:
    void solve(istream& in, ostream& out) {
        int n, s;
        in >> n >> s;
        vector<int> a(n);
        for (int i = 0; i < n; ++i)
            in >> a[i];
        a.erase(max_element(a.begin(), a.end()));
        for (int v : a)
            s -= v;
        out << (s >= 0 ? "YES" : "NO") << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);
    A426 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
