/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class A453 {
public:
    void solve(istream& in, ostream& out) {
        int m, n;
        in >> m >> n;
        
        double res = 0;
        for (int i = 1; i <= m; ++i) {
            res += i * (pow(i/(double)m, n) - pow((i-1)/(double)m, n));
        }
        out.precision(17);
        out << fixed << res << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    A453 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
