/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class A69 {
public:
    void solve(istream& in, ostream& out) {
        int n, x = 0, y = 0, z = 0;
        in >> n;
        for (int i = 0; i < n; ++i) {
            int tx, ty, tz;
            in >> tx >> ty >> tz;
            x += tx;
            y += ty;
            z += tz;
        }
        out << (x || y || z ? "NO\n" : "YES\n");
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    A69 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
