/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class TaskA {
public:
    void solve(istream& in, ostream& out) {
        int n, cnt1 = 0, cnt2 = 0;
        in >> n;
        for (int i = 0; i < n; ++i) {
            int m, c;
            in >> m >> c;
            cnt1 += (m > c);
            cnt2 += (c > m);
        }
        if (cnt1 > cnt2) {
            out << "Mishka\n";
        } else if (cnt1 < cnt2) {
            out << "Chris\n";
        } else {
            out << "Friendship is magic!^^" << "\n";
        }
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    TaskA solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
