/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class TaskA {
public:
    void solve(istream& in, ostream& out) {
        vector<int> l(4), s(4), r(4), p(4);
        for (int i = 0; i < 4; ++i) {
            in >> l[i] >> s[i] >> r[i] >> p[i];
        }
        
        for (int i = 0; i < 4; ++i) {
            if (p[i]) {
                if (r[(i - 1 + 4) % 4] || l[(i + 1) % 4] || s[(i + 2) % 4]) {
                    out << "YES\n";
                    return;
                }
                if (r[i] || l[i] || s[i]) {
                    out << "YES\n";
                    return;
                }
            }
        }
        out << "NO\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    TaskA solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
