/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class TaskA {
public:
    void solve(istream& in, ostream& out) {
        int n, k;
        in >> n >> k;
        vector<int> a(n);
        int sum = 0;
        for (int i = 0; i < n; ++i) {
            in >> a[i];
            sum += a[i];
        }
        
        int add = 0;
        double avg = ((double)(sum) / n);
        //cout << sum << " " << avg << endl;
        while (avg < k - 0.5) {
            ++add;
            avg = ((double)(sum + add * k ) / (n + add));
            //cout << sum + add * k << " " << avg << endl;
        }
        
        out << add << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    TaskA solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
