/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <cassert>

using namespace std;

typedef vector<int> vi;
typedef vector<vi> vvi;
typedef vector<pair<int,int>> vii;

class arc068C {
public:
    void solve(istream& in, ostream& out) {
        int64_t x;
        in >> x;
        
        int64_t num = x / (6 + 5);
        
        x -= num * 11;
        
        int64_t res = num * 2;
        while (x > 0) {
            x -= 6;
            ++res;
            if (x <= 0) {
                break;
            }
            x -= 5;
            ++res;
        }
        
        out << res << endl;
        
    }
};


int main() {
    std::ios::sync_with_stdio(false);

    arc068C solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
