/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin64b
 */

#include <fstream>

#include <iostream>
#include <string>

using namespace std;

class TaskA {
public:
    void solve(std::istream& in, std::ostream& out) {
        int n;
        in >> n;

        int k = 0;
        string res;
        if (n % 2 == 1) {
            ++k;
            n -= 3;
            res += "3 ";
        }

        k += n / 2;
        while (n) {
            res += "2 ";
            n -= 2;
        }
        out << k << std::endl;
        out << res << std::endl;

    }
};


int main() {
    TaskA solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}