/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <cassert>

using namespace std;

class TaskA {
public:
    bool isPrime(int x) {
        for (int i = 2; i*i <= x; ++i) {
            if (x % i == 0) {
                return false;
            }
        }
        return true;
    }
    void solve(istream& in, ostream& out) {
        int n;
        in >> n;
        
        for (int m = 1; m <= 1000; ++m) {
            if (!isPrime(n*m+1)) {
                out << m << endl;
                return;
            }
        }
    }
};


int main() {
    std::ios::sync_with_stdio(false);

    TaskA solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
