/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>

using namespace std;

class aoc14_2 {
private:
    string to_binary(int x) {
        string binary;
        int num = 0;
        while (x) {
            binary += to_string(x % 2);
            x /= 2;
            ++num;
        }
        while (num < 4)
            binary += "0", ++num;
        return binary;
    }
    string knot_hash(const string& input) {
        constexpr int n = 256;
        vector<int> lst(n);
        for (int i = 0; i < n; ++i)
            lst[i] = i;
        vector<int> lens;
        for (char c : input)
            lens.push_back(c);
        for (int x : {17, 31, 73, 47, 23})
            lens.push_back(x);
        int m = lens.size();
        int cur = 0, skip = 0;
        for (int round = 0; round < 64; ++round) {
            for (int j = 0; j < m; ++j) {
                int len = lens[j];
                for (int i = 0; i < len / 2; ++i) {
                    int a = (cur + i) % n;
                    int b = (cur + len - 1 - i) % n;
                    swap(lst[a], lst[b]);
                }
                cur += len + skip;
                cur %= n;
                ++skip;
            }
        }
        vector<int> dense(16);
        for (int i = 0; i < 16; ++i) {
            for (int j = i * 16; j < (i + 1) * 16; ++j) {
                dense[i] ^= lst[j];
            }
        }
        string binary;
        for (int i = 15; i >= 0; --i) {
            int a = dense[i] % 16, b = dense[i] / 16;
            binary += to_binary(a) + to_binary(b);
        }
        reverse(binary.begin(), binary.end());
        return binary;
    }
    int dirx[4]{1, -1, 0, 0};
    int diry[4]{0, 0, 1, -1};
    void dfs(int x, int y, const vector<string>& g, vector<vector<int>>& vis) {
        for (int i = 0; i < 4; ++i) {
            int nx = x + dirx[i], ny = y + diry[i];
            if (nx >= 0 && nx < 128 && ny >= 0 && ny < 128 && !vis[nx][ny] && g[nx][ny] == '1') {
                vis[nx][ny] = vis[x][y];
                dfs(nx, ny, g, vis);
            }
        }
    }
public:
    void solve(istream& in, ostream& out) {
        const string s = "ugkiagan-";
        vector<string> g;
        for (int i = 0; i < 128; ++i) {
            string input = s + to_string(i);
            string khash(knot_hash(input));
            g.push_back(khash);
        }
        vector<vector<int>> vis(128, vector<int>(128, 0));
        int comp_id = 0;
        for (int i = 0; i < 128; ++i) {
            for (int j = 0; j < 128; ++j) {
                if (!vis[i][j] && g[i][j] == '1') {
                    vis[i][j] = ++comp_id;
                    dfs(i, j, g, vis);
                }
            }
        }
        out << comp_id << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    aoc14_2 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
