/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <fstream>

#include <iostream>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>
#include <map>
#include <set>
#include <cmath>
#include <cstdlib>
#include <tuple>
#include <queue>
#include <functional>
#include <stack>
#include <numeric>
#include <cassert>
#include <sstream>

using namespace std;

class aoc12_1 {
private:
    int dfs(int u, const vector<vector<int>>& g, vector<int>& vis) {
        vis[u] = 1;
        int res = 1;
        for (int v : g[u]) {
            if (!vis[v])
                res += dfs(v, g, vis);
        }
        return res;
    }
public:
    void solve(istream& in, ostream& out) {
        string s;
        vector<vector<int>> g;
        while (getline(in, s)) {
            stringstream ss(s);
            int u, v;
            g.push_back({});
            string trash;
            ss >> u >> trash;
            while (ss >> v) {
                g[u].push_back(v);
                ss >> trash;
            }
        }
        vector<int> vis(g.size(), 0);
        out << dfs(0, g, vis) << "\n";
    }
};


int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);

    aoc12_1 solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
