/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <bits/stdc++.h>

using namespace std;

class TaskA {
public:
    void solve(istream& in, ostream& out) {
        int n;
        in >> n;
        vector<int> v(2 * n);
        set<int> st;
        for (int i = 0; i < 2 * n; ++i) {
            in >> v[i];
            st.insert(v[i]);
        }
        int num = 0;
        for (int x = 0; x < n; ++x) {
            for (int y = n; y < 2 * n; ++y) {
                num += st.count(v[x] ^ v[y]);
            }
        }
        out << ((num % 2) ? "Koyomi" : "Karen") << "\n";
    }
};

int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);
    TaskA solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
