/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author yassin
 */

#include <bits/stdc++.h>

using namespace std;

class TaskB {
public:
    void solve(istream& in, ostream& out) {
        unsigned long long a, b;
        in >> a >> b;
        unsigned long long last = 1;
        for (++a; a <= b; ++a) {
            last *= a;
            last %= 10;
            if (last == 0) {
                break;
            }
        }
        out << last << "\n";
    }
};

int main() {
    std::ios::sync_with_stdio(false); cin.tie(nullptr);
    TaskB solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
